name: usb_serial_communication
description: "A new Flutter plugin about usb serial communication"
version: 0.0.2
homepage: https://github.com/Moein-dev/usb_serial_communication

environment:
  sdk: ^3.5.4
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:

  plugin:
    platforms:
      android:
        package: com.pos.usb_serial_communication
        pluginClass: UsbSerialCommunicationPlugin

